### ISSUE TITLE
Cannot follow the steps to clone the repository

### ISSUE THREAD

**Issue by GTCCApplications** [ellucian-developer/experience-productivity-extensions#14]
The instructions for this repository do not work properly. It appears to always want to connect to your github instance. Despite deleting the .git folder, forking the repo, etc. We would love to have the Google/Microsoft cards this repo provides. Following the steps below produce errors and an empty node_modules folder. Please note, we are able to successfully create an extension example of our own using https://resources.elluciancloud.com/bundle/ellucian_experience_acn_use/page/t_create_extension.html. The SDK commands are not recognized when attempting to follow the exact instructions in this repo.

The custom extension of our own uploads to our instance just fine using the token, but for some reason this repo doesn't allow similar set up. We have attached our log files for your records. Please let me know what we might be doing incorrectly.

![image](https://user-images.githubusercontent.com/84813096/162315020-bcf3139b-d9fe-43ec-9223-19a52404240d.png)

[2022-04-07T21_12_59_158Z-debug.log](https://github.com/ellucian-developer/experience-productivity-extensions/files/8446571/2022-04-07T21_12_59_158Z-debug.log)

**Comment by ellucianBret** [comment]
@GTCCApplications what version of node are you using?

Can you try this with node version 14 or higher?

This issue is with how node/npm is accessing Github's repository. The version you are using requires that you have a Github ssh key configured.

Bret

**Comment by ellucianBret** [comment]
Oh my, the dependency on the experience-extension-hooks was archived and made private prematurely!

I just make it public again. Please try now.

Sorry,
Bret

**Comment by GTCCApplications** [comment]
@ellucianBret Seems to have worked! Going to begin the rest of the configuration.

**Comment by ellucianBret** [comment]
Awesome!

Sorry about that. I will be updating this to use the latest Experience SDK and this dependency will go away.

Bret
